image: python:3.7.3

definitions:
  caches:
    sonar: ~/.sonar/cache
    pip: ~/.cache/pip

  services:
    docker:
      memory: 2048

  steps:
    - step: &coverage
        name: Coverage and Sonar Scan
        size: 2x
        caches:
          - pip
          - sonar
          - docker
        services:
          - docker
        script:
          - python run.py setup
          - python run.py coverage/xml
          - pipe: sonarsource/sonarcloud-scan:1.0.1
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.3

pipelines:
  branches:
    dev:
      - step: *coverage
  pull-requests:
    '**':
      - step: *coverage